Repository Ucommercenet/Avenue-Clothing-For-Umbraco, pull requests merged in 2020-03, with the labels that each got.

#11 Adjust controllers
  src/Ucommerce.Avenue.Umbraco/Controllers/PartialViewController.cs
  src/Ucommerce.Avenue.Umbraco/Controllers/ProductController.cs
Labels: enhancement

#17 Enable selection of variants
  src/Ucommerce.Avenue.Umbraco/Controllers/RouterController.cs
Labels: bug, enhancement

#21 Use fewer queries to fill the "category page with product listing"
  src/Ucommerce.Avenue.Umbraco/Api/AvenueClothingApiProductController.cs
  src/Ucommerce.Avenue.Umbraco/Controllers/BillingController.cs
  src/Ucommerce.Avenue.Umbraco/Controllers/CategoryController.cs
  src/Ucommerce.Avenue.Umbraco/Controllers/EmailController.cs
  src/Ucommerce.Avenue.Umbraco/Controllers/RouterController.cs
  src/Ucommerce.Avenue.Umbraco/Controllers/ShippingController.cs
  src/Ucommerce.Avenue.Umbraco/Views/Catalog.cshtml
  src/Ucommerce.Avenue.Umbraco/scripts/uCommerce.category.js
Labels: enhancement

#14 Fix: Avenue was always redirecting to confirmation, even when a payme…
  src/uCommerce.RazorStore/Controllers/BasketpreviewController.cs
Labels: bug
